### ISSUE TITLE
class.simple_html_dom.php on line 1364

### ISSUE THREAD

**Issue by hasankaraagac** [erdemarslan/namazvakti#10]
Üstad hizmetiniz için çok teşekkür ederim.
Aşağıdaki hatayı alıyorum ve namaz vakitleri gelmiyor?

Warning:  preg_match(): Compilation failed: invalid range in character class at offset 4 in /namazvakti-master/class.simple_html_dom.php on line 1364

nasıl çözebiliriz?

**Comment by erdemarslan** [comment]
Merhabalar, muhtemelen Diyanet yine veri sayfasını değiştirdi. Sınıf veriyi doğru alamadığı için yardımcı sınıf da veriyi doğru okuyamıyor ve hata veriyor. Bu sıralar başka işlerden dolayı buna vakit ayıramıyorum. Bu sınıfları github üzerine koymamın temel amacı insanlar da eksiklikleri görsün ve düzeltsin idi. Malesef insanımız bu konuda pek de başarılı değil. Sınıfı alıp kullanan onlarda backend developer var. Sınıf hata vermeye başladığında sistemlerinde düzenlemeleri yapmışlar ve hata sınıf sistemlerinde çalışıyor ancak buraya güncelleme ekleme konusunda pek de istekli değiller. Böyle giderse bu tür sınıfların arkasındaki desteğimi çekeceğim. Güncelleme yaptığımda sorunu tekrardan ele alırım. Ancak çok kısa sürede beklemeyin lütfen.

**Comment by hasankaraagac** [comment]
Öncelikle zaman ayırıp cevap verdiğiniz için teşekkür ederim.
Localde çalışıyor. Ben araştırdım fakat çalışması için gereksinimlerini
tespit edememiştim. Artık localde çalışmanın bir yolunu buldum.

İyi çalışmalar...

Erdem Arslan <notifications@github.com>, 3 May 2020 Paz, 01:05 tarihinde
şunu yazdı:
