### ISSUE TITLE
Warning on japanese hosting server (Sakura)

### ISSUE THREAD

**Issue by naimbic** [erdemarslan/namazvakti#4]
Hello, thank you for this code, it help me a lot for study case.

i got this `Warning:  Invalid argument supplied for foreach() in /.../www/namaz_PHP/namazvakti_class/class.namazvakti.php on line 35`

i tested on other server like host gator and its working fine!
Any help please, thank you

**Comment by erdemarslan** [comment]
All codes are changed. Please retry codes on your host.
I closed the topic. If you have any problem, please re open it.

Thanks.
