### ISSUE TITLE
URL Issue

### ISSUE THREAD

**Issue by Kurbzz** [erdemarslan/namazvakti#6]
Slm,

Sehir lerde space oldugu zaman, url yanlis oluyor.

Vakit() methodunda, buralari (line 173 ve 177) degistirseniz iyi olur : 

       `$url = $this->server . $this->ilce . "/" . strtolower($ilce['veri'][$this->ilce]) . "-icin-namaz-vakti";`

->

       `$url = $this->server . $this->ilce . "/" . str_replace(' ', '-',trim(strtolower($ilce['veri'][$this->ilce]))) . "-icin-namaz-vakti";`

**Comment by erdemarslan** [comment]
Teşekkürler. Düzeltme yapıldı.
