### ISSUE TITLE
İl ve ilçeleri çağırma 

### ISSUE THREAD

**Issue by AltanAdacay** [erdemarslan/namazvakti#8]
Merhaba Erdem,  $namaz->ulke(2)->il(521)->ilce(9348); Şekliyle ülke ve şehirleri çağırabiliyoruz.
Peki bunu; $namaz->ulke('TURKIYE')->il('ANTALYA')->ilce('ALANYA'); gibi isimlerle çağırabilmemiz mümkün mü?

**Comment by erdemarslan** [comment]
Kodlarda değişiklik yapmak gerekir. Veritabanı kullanılırsa neden olmasın!
