### ISSUE TITLE
Hata

### ISSUE THREAD

**Issue by esginmurat** [erdemarslan/namazvakti#9]
Merhabalar. Öncelikle teşekkürler. Localhost'a yükledim lakin çağırdığımda ekran görüntüsündeki gibi gözüküyor. php 7.2 +apache var. Ek ne yüklemem gerekir? Şimdiden teşekkürler.
![ekran](https://user-images.githubusercontent.com/17769013/50023258-aed10280-ffef-11e8-8848-b653f0812ea6.png)

**Comment by pxqopat-g** [comment]
Selam,

Göründüğü kadarıyla çalışıyor zaten hata mesajı almamışsın. Kendi isteklerin doğrultusunda kodu değiştirmen veya kullanman gerek.

Android için Outlook<https://aka.ms/ghei36> uygulamasını edinin

________________________________

**Comment by esginmurat** [comment]
Teşekkürler.
